#!/bin/bash -eu

SOURCE_PATH=${SOURCE_PATH:-}
GENERATED_DOCKERFILES_PATH=${GENERATED_DOCKERFILES_PATH:-}

if [[ -z ${SOURCE_PATH} ]]; then
    SOURCE_PATH="$(readlink -f "$(dirname "${0}")"/..)"
fi

if [[ -z "${GENERATED_DOCKERFILES_PATH}" ]]; then
    GENERATED_DOCKERFILES_PATH="$(readlink -f "${SOURCE_PATH}/generated_dockerfiles")"
    mkdir -p "${GENERATED_DOCKERFILES_PATH}"
fi

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-config "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.20-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/iaas-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.20-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/aws-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.20-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-aws-kv1-20.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/aws-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.19-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-aws-kv1-19.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/aws-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.18-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-aws-kv1-18.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/aws-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.17-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-aws-kv1-17.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/az-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.20-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-az-kv1-20.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/az-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.19-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-az-kv1-19.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/az-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.18-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-az-kv1-18.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/az-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.17-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-az-kv1-17.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gcp-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.20-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-gcp-kv1-20.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gcp-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.19-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-gcp-kv1-19.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gcp-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.18-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-gcp-kv1-18.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gcp-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.17-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-gcp-kv1-17.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/openstack-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.20-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-openstack-kv1-20.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/openstack-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.19-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-openstack-kv1-19.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/openstack-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.18-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-openstack-kv1-18.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/openstack-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.17-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-openstack-kv1-17.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/aliyun-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.20-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-aliyun-kv1-20.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/aliyun-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.19-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-aliyun-kv1-19.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/aliyun-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.18-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-aliyun-kv1-18.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/aliyun-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectlv1.17-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl-aliyun-kv1-17.dockerfile