#!/bin/bash -eu

SOURCE_PATH=${SOURCE_PATH:-}
GENERATED_DOCKERFILES_PATH=${GENERATED_DOCKERFILES_PATH:-}

if [[ -z ${SOURCE_PATH} ]]; then
    SOURCE_PATH="$(readlink -f "$(dirname "${0}")"/..)"
fi

if [[ -z "${GENERATED_DOCKERFILES_PATH}" ]]; then
    GENERATED_DOCKERFILES_PATH="$(readlink -f "${SOURCE_PATH}/generated_dockerfiles")"
    mkdir -p "${GENERATED_DOCKERFILES_PATH}"
fi

latest_kv=`cat "${SOURCE_PATH}"/.ci/k8s_versions |head -1`
cat > "${SOURCE_PATH}"/dockerfile-configs/kubectl-components.yaml << EOF
    - curl:
      - name: kubectl
        version: v$latest_kv
        from: https://storage.googleapis.com/kubernetes-release/release/v$latest_kv/bin/linux/amd64/kubectl
        info: command line tool for controlling Kubernetes clusters.
EOF

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-config "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectl-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt.dockerfile

"${SOURCE_PATH}"/generator/generate-dockerfile.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/iaas-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectl-components.yaml \
    --from-image ubuntu:18.04 \
    --title "gardener shell" \
    --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-gardenctl.dockerfile

for kv in `cat "${SOURCE_PATH}"/.ci/k8s_versions`
do
    kv_short=`echo $kv |cut -d '.' -f 1,2`
    cat > "${SOURCE_PATH}"/dockerfile-configs/kubectl-components.yaml << EOF
            - curl:
              - name: kubectl
                version: v$kv
                from: https://storage.googleapis.com/kubernetes-release/release/v$kv/bin/linux/amd64/kubectl
                info: command line tool for controlling Kubernetes clusters.
EOF
    for iaas_provider in `cat "${SOURCE_PATH}"/.ci/iaas_providers`
    do
        "${SOURCE_PATH}"/generator/generate-dockerfile.py \
            --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
            --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/$iaas_provider-components.yaml \
            --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gardenctl-components.yaml \
            --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/kubectl-components.yaml \
            --from-image ubuntu:18.04 \
            --title "gardener shell" \
            --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-$iaas_provider-k$kv_short.dockerfile

    done
done
rm "${SOURCE_PATH}"/dockerfile-configs/kubectl-components.yaml
