#!/bin/bash -eu

SOURCE_PATH=${SOURCE_PATH:-}
GENERATED_DOCKERFILES_PATH=${GENERATED_DOCKERFILES_PATH:-}

if [[ -z "${SOURCE_PATH}" ]]; then
    SOURCE_PATH="$(readlink -f "$(dirname "${0}")"/..)"
fi

"${SOURCE_PATH}"/generator/validate-tools.py \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/common-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/iaas-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/aws-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/az-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/gcp-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/openstack-components.yaml \
    --dockerfile-configs "${SOURCE_PATH}"/dockerfile-configs/aliyun-components.yaml