#! /usr/bin/env bash

set -e
set -o pipefail

SOURCE_PATH=${SOURCE_PATH:-}
PYTHON="${VENV_PYTHON:-python3}"

if [[ -z ${SOURCE_PATH} ]]; then
    SOURCE_PATH="$(readlink -f "$(dirname "${0}")"/..)"
fi
cd "${SOURCE_PATH}" || exit 1

if [ "${DESTINATION}" == "" ]; then
    "${PYTHON}" -m bandit --format sarif -r src
    exit
fi

${PYTHON} -m bandit --format sarif -r src | tee "${DESTINATION}"
