#!/bin/bash
# Copyright 2019 Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

home="$1"
folder="$2"
article="$3"

[[ "$home" == "/" ]] && home=""

if [[ -f "$home/$folder/$article" ]]; then
  command -v mdv && mdv "$home/$folder/$article" || cat "$home/$folder/$article"
elif [[ -f "$home/$folder/$article.md" ]]; then
  command -v mdv && mdv "$home/$folder/$article.md" || cat "$home/$folder/$article.md"
else
  findings_made=false
  findings="$(find "$home/$folder" -iname "*$article*" | sed -r "s;${home}/$folder/(.*).md;- \1;g")"
  [[ ! -z "$findings" ]] && findings_made=true && echo -e "\nDid you mean (by article name)?\n\n$findings" | grep --color -E "$article|$"

  findings="$(grep -r -i "$article" "$home/$folder" | sed -r "s;${home}/$folder/(.*).md;- \1;g")"
  [[ ! -z "$findings" ]] && findings_made=true && echo -e "\nDid you mean (by article content)?\n\n$findings" | grep --color -E "$article|$"

  ! $findings_made && echo -e "\nI cannot find anything with this name or content!"
fi
