#!/bin/bash

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

home="$1"
folder="$2"
article="$3"

[[ "$home" == "/" ]] && home=""

if [[ -f "$home/$folder/$article" ]]; then
  command -v mdv && mdv "$home/$folder/$article" || cat "$home/$folder/$article"
elif [[ -f "$home/$folder/$article.md" ]]; then
  command -v mdv && mdv "$home/$folder/$article.md" || cat "$home/$folder/$article.md"
else
  findings_made=false
  findings="$(find "$home/$folder" -iname "*$article*" | sed -r "s;${home}/$folder/(.*).md;- \1;g")"
  [[ ! -z "$findings" ]] && findings_made=true && echo -e "\nDid you mean (by article name)?\n\n$findings" | grep --color -E "$article|$"

  findings="$(grep -r -i "$article" "$home/$folder" | sed -r "s;${home}/$folder/(.*).md;- \1;g")"
  [[ ! -z "$findings" ]] && findings_made=true && echo -e "\nDid you mean (by article content)?\n\n$findings" | grep --color -E "$article|$"

  ! $findings_made && echo -e "\nI cannot find anything with this name or content!"
fi
