#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

from tabulate import tabulate
import json
import textwrap
import subprocess
import os

def parse_package_info(package_info, provided_binaries, name_key, version_key, info_key):
    lines = package_info.split('\n')
    name = ""
    version = ""
    info = ""
    for line in lines:
        if line.startswith(name_key):
            name = line.split(":", 1)[1].strip()
            binaries = provided_binaries[name]
            if type(binaries) == list:
                binaries = ' '.join(binaries)
        if line.startswith(version_key):
            version = line.split(":", 1)[1].strip()
        if line.startswith(info_key):
            info = line.split(":", 1)[1].strip()
    return [binaries, version, info]

def retrieve_packages_info(installed_tools_list, package_manager, show_command, version_delimiter, delimiter, name_key, version_key, info_key):
    tools = []
    provided_binaries = {}
    tool_names = []
    for entry in installed_tools_list:
        nameWithoutVersion = entry[0].split(version_delimiter)[0]
        tool_names.append(nameWithoutVersion)
        provided_binaries[nameWithoutVersion] = entry[1]
    command = [package_manager, show_command]
    command.extend(tool_names)
    output = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True, universal_newlines=True)
    tool_infos = output.stdout.rstrip("\n").split(delimiter)
    for tool_info in tool_infos:
        tool = parse_package_info(tool_info, provided_binaries, name_key, version_key, info_key)
        tools.append(tool)
    return tools

def retrieve_downloaded_tools_info(downloaded_tools):
    tools = []
    for tool in downloaded_tools:
        tools.append([tool[0], tool[1], tool[2]])

    return tools

def retrieve_hacks_info():
    tools = [
        ["install_k9s", "LATEST", "Install k9s: curses based terminal UI to interact with your Kubernetes clusters."],
        ["ops-pod", "", "Start an ops-toolbelt container in a k8s cluster"],
    ]

    return tools


ghelp_info_path="/var/lib/ghelp_info"
ghelp_info = None
with open(ghelp_info_path, "r") as f:
    ghelp_info = json.load(f)

if ghelp_info is None:
    print("Failed to load ghelp info")
    exit(1)

apttools = retrieve_packages_info(ghelp_info["apt"], "apt", "show", "=", "\n\n" , "Package", "Version", "Description")
downloaded_tools = retrieve_downloaded_tools_info(ghelp_info["downloaded"])
hack_tools = retrieve_hacks_info()

table = []
table.extend(apttools)
table.extend(downloaded_tools)
table.extend(hack_tools)

terminal_width = os.get_terminal_size().columns
max_name_width = (terminal_width-10)//4
max_info_width = (terminal_width-10)//2

for i in range(len(table)):
    table[i][0] = textwrap.fill(table[i][0], width=max_name_width)
    if table[i][1] is not None:
         table[i] [1] = textwrap.fill(table[i][1], width=max_name_width)
    table[i][2] = textwrap.fill(table[i][2], width=max_info_width)

table_headers = ["TOOL/PACKAGE", "VERSION", "NOTES"]
table_headers[0] = textwrap.fill(table_headers[0], width=max_name_width)
table_headers[1] = textwrap.fill(table_headers[1], width=max_name_width)
table_headers[2] = textwrap.fill(table_headers[2], width=max_name_width)

print(tabulate(table, table_headers, tablefmt="grid"))
