#!/bin/bash -e

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

function show_help () {
  echo "Usage: ${0} [arguments]"
  echo "Possible arguments:"
  echo "-h, --help       Show this help message and exit"
  echo "-v, --version    Optional: specify k9s version to use. Default: latest version will be installed"
}

function install () {
  local version=$1
  local download_url
  local arch=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')

  if [ -z "$version" ]
  then # fetch latest
    local latest_release=$(curl -sL https://api.github.com/repos/derailed/k9s/releases/latest)
    version=$(echo "${latest_release}" | jq -r '.tag_name')
    echo "installing latest version ${version}"
    download_url=$(echo "${latest_release}" | jq -r --arg filename "k9s_Linux_${arch}.tar.gz" '.assets[] | select(.name == $filename) | .browser_download_url')
  else
    if [[ ! $version == v* ]]
    then
      version="v${version}"
    fi
    echo "installing k9s version ${version}"
    download_url="https://github.com/derailed/k9s/releases/download/${version}/k9s_Linux_${arch}.tar.gz"
  fi

  curl -sL ${download_url} -o k9s.tar.gz && tar -zxvf k9s.tar.gz k9s && mv k9s /usr/local/bin/k9s && chmod 755 /usr/local/bin/k9s && rm k9s.tar.gz

  echo "You can now start using k9s. Just execute \"k9s\" to use it or \"k9s -n mynamespace\" to target a namespace. See https://github.com/derailed/k9s for more details."
}

case "$1" in
  --version | -v)
    install "$2"
    exit
    ;;
  --help | -h)
    show_help
    exit
    ;;
  *)
    install
    exit
    ;;
esac
