#!/bin/bash -e

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

function show_help () {
  echo "Usage: ${0} [arguments]"
  echo "Possible arguments:"
  echo "-h, --help       Show this help message and exit"
  echo "-v, --version    Optional: specify k9s version to use. Default: latest version will be installed"
}

function install () {
  local version=$1
  local download_url
  local yellow="\033[0;33m"
  local nc="\033[0m"
  local arch
  local platform
  local pkg
  local dest
  local version_url="https://api.github.com/repos/derailed/k9s/releases/latest"

  tmp_dir="$(mktemp -d)"
  mkdir -p "${tmp_dir}/dest"

  dest="/opt/bin/k9s"
  if uname="$(whoami 2> /dev/null)"; then
    if [[ "${uname}" == "root" ]]; then
      if [ -w "/usr/local/bin" ]; then
        dest="/usr/local/bin/k9s"
      fi
    fi
  fi

  arch=$(uname -m | sed 's/^x86_64$/amd64/;s/^aarch64$/arm64/')

  platform="$(uname -s)"
  pkg="k9s_${platform}_${arch}"

  if [ -z "$version" ]; then # fetch latest
    version=$(curl -sL "${version_url}" | jq -r '.tag_name')
  fi

  if [[ ! $version == v* ]]; then
    version="v${version}"
  fi

  download_url="https://github.com/derailed/k9s/releases/download/${version}/${pkg}.tar.gz"

  curl -sL "${download_url}" \
    -o "${tmp_dir}/${pkg}.tar.gz" && \
    tar -zxf "${tmp_dir}/${pkg}.tar.gz" -C "${tmp_dir}/dest" && \
    mv "${tmp_dir}/dest/k9s" "${dest}" && \
    chmod 755 "${dest}" && \
    rm -rf "${tmp_dir}"

  echo -e "${yellow}"
  echo "You can now start using k9s. Just execute \"k9s\" to use it or \"k9s -n mynamespace\" to target a namespace. See https://github.com/derailed/k9s for more details."
  echo -e "${nc}"
}

case "$1" in
  --version | -v)
    install "$2"
    exit
    ;;
  --help | -h)
    show_help
    exit
    ;;
  *)
    install
    exit
    ;;
esac
