#!/bin/bash -e

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

function show_help () {
  echo "Usage: ${0} [arguments]"
  echo "Possible arguments:"
  echo "-h, --help       Show this help message and exit"
  echo "-v, --version    Optional: specify etcdctl version to use. Default: version v3.4.26 will be installed."
}

function install () {
  local version="${1:-v3.4.30}" # default version "v3.4.3
  local download_url
  local arch
  local platform
  local pkg
  local dest

  if [[ $(whoami) == "root" ]]; then
    dest="/usr/local/bin/etcdctl"
  else
    dest="${DOTFILES_HOME}/bin/etcdctl"
  fi
  arch="$(arch)"
  case "${arch}" in
    x86_64)
      arch="amd64"
      ;;
    arm64)
      arch="arm64"
      ;;
  esac

  platform="$(uname -s | tr '[:upper:]' '[:lower:]')"
  pkg="etcd-${version}-${platform}-${arch}"

  echo "installing etcdctl version ${version}"
  download_url="https://github.com/coreos/etcd/releases/download/${version}/${pkg}.tar.gz"

  curl -sL "${download_url}" \
    -o "${pkg}.tar.gz" && \
    tar -zxvf "${pkg}.tar.gz" && \
    mv "${pkg}/etcdctl" "${dest}" && \
    rm "${pkg}.tar.gz" && \
    rm -r "${pkg}"
  echo "You can now start using etcdctl. Just execute \"etcdctl\" to use it. See https://etcd.io/docs/v3.4/dev-guide/interacting_v3/ for more details."
  echo "This tool assumes that it is being run in an ephemeral container in a pod. If this is not the case, please ensure that you provide the correct certificates, the correct endpoint, and have all necessary accesses."
  echo "Certificates to be passed to the command should be mounted onto any container in the pod having a shared process namespace. Please run \"ps -A\" to list all processes and then access the certificates using \"/proc/<proc number>/root/<file-path>\". Pass these certificate file paths to the etcdctl command :)"
}

case "$1" in
  --version | -v)
    install "$2"
    exit
    ;;
  --help | -h)
    show_help
    exit
    ;;
  *)
    install
    exit
    ;;
esac
