#!/bin/bash

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

home="$(dirname "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")")"
"$home/hacks/find-and-show-in-guide" "$home/guide/01_Operations" "01_Play_Books" "$1"
