name: Create Upgrade-Pull-Requests
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  upgrade-pullrequests:
    if: ${{ github.repository_owner == 'gardener' }}
    uses: gardener/cc-utils/.github/workflows/upgrade-dependencies.yaml@master
    secrets: inherit
    permissions:
      contents: write
      id-token: write
